<!DOCTYPE html>
<html>
<head>
    <title>City lists</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/life-bot/bower_components/pure/pure-min.css">
    <link rel="stylesheet" href="/life-bot/assets/css/side-menu.css">
</head>
<body>
    <div id="layout">
        <div id="main">
        <div class="header">
            <h1>城市對照清單</h1>
            <h2>動態公車輸入城市名稱用</h2>
        </div>
        <div class="content">
            <h2 class="content-subhead">中英對照表</h2>
            <table class="pure-table table-width">
                <thead>
                    <tr>
                        <th>編號</th>
                        <th>中文名稱</th>
                        <th>英文名稱</th>
                    </tr>
                </thead>
                <tbody>

                <?php
                    if(isset($data["cities"])) {
                        echo $data["cities"];
                    }
                ?>

                </tbody>
            </table>
        </div>
        </div>
    </div>
</body>
</html>
