<!DOCTYPE html>
<html>
<head>
    <title>City lists</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/life-bot/bower_components/pure/pure-min.css">
    <link rel="stylesheet" href="/life-bot/assets/css/side-menu.css">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
</head>
<body>
    <div id="layout">
        <div id="main">
        <div class="header">
            <h1>公車動態</h1>
            <h2>查詢結果</h2>
        </div>
        <div class="content">
            <h2 class="content-subhead">動態公車表</h2>
            <?php
                if(isset($data["route_name"])) {
                    echo $data["route_name"];
                }
            ?>
            <table class="pure-table table-width">
                <thead>
                    <tr>
                        <th>去程/回程</th>
                        <th>站牌名稱</th>
                        <th>預估到站時間</th>
                    </tr>
                </thead>
                <tbody>

                <?php
                    if(isset($data["cities"])) {
                        echo $data["cities"];
                    }
                ?>

                </tbody>
            </table>
        </div>
        </div>
    </div>
</body>
</html>
