
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>0118</title>
<link href="https://code.essoduke.org/css/style.css" rel="stylesheet" />
<style>
.map{width:100%;height:480px}
</style>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <select id="travel">
                    <option value="driving">開車</option>
                    <option value="transit">大眾運輸</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div id="info"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div id="map" class="map"></div>
            </div>
            <div class="col-md-6">
                <div id="panel"></div>
            </div>
        </div>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://code.essoduke.org/js/tinyMap/jquery.tinyMap-3.3.14.min.js"></script>
<script>
(function () {

    var map    = $('#map'),
        marker = $('#info'),
        panel  = $('#panel'),
        info   = $('#info'),
        // Direction data
        data   = {
            'from'  : '100台北市中正區南海路56 號',
            'to'    : '111台北市士林區至善路二段221號',
            'travel': 'driving',
            'panel' : panel,
            'event' : {
                'directions_changed': function () {
                    var direction = this.getDirections(),
                        html = [];

                    info.empty();

                    // direction.routes[n] 表示第 N 段規劃的路徑
                    // direction.routes[n].legs 該路段細節
                    if (direction) {
                        info.append(direction.routes[0].legs[0].distance.text)
                            .append(direction.routes[0].legs[0].duration.text);
                    }
                }
            }
        };

    // 初始化 tinyMap
    map.tinyMap({
        'center': ['25.037627167884715', '121.56732559204102'],
        'zoom'  : 12,
        'direction': [data]
    });

    $(document)
        // 變更交通方式
        .on('change', '#travel', function () {
            data.travel = this.value;
            panel.empty();
            map.tinyMap('clear')
               .tinyMap('modify', {
                   'direction': [data]
               });
        })
}());
</script>
</body>
</html>
