
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>伴手禮</title>
<link href="https://code.essoduke.org/css/style.css" rel="stylesheet" />
<style>
.map{width:100%;height:480px}
</style>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div id="info"></div>
            </div>
        </div>
        <div class="row">
            {{ map_image|raw }}
        </div>
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <td>屆別</td>
                        <td>得獎產品名稱</td>
                        <td>店家名稱</td>
                        <td>地址</td>
                        <td>電話</td>
                        <td>店家網頁</td>
                    </tr>
                </thead>
                <tbody>
                    {{ souvenir_map_random|raw }}
                </tbody>
            </table>
        </div>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://code.essoduke.org/js/tinyMap/jquery.tinyMap-3.3.14.min.js"></script>
<script>
(function () {
}());
</script>
</body>
</html>
