<!DOCTYPE html>
<html>
<head>
    <title>Usage command lists</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="bower_components/pure/pure-min.css">
    <link rel="stylesheet" href="assets/css/side-menu.css">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/icon/favicon-16x16.png">
</head>
<body>
    <div id="layout">
        <div id="main">
        <div class="header">
            <h1>幫助我</h1>
            <h2>life-bot 使用方式</h2>
        </div>
        <div class="content">
            <h2 class="content-subhead">指令對照表</h2>
            <table class="pure-table table-width">
                <thead>
                    <tr>
                        <th>指令</th>
                        <th>結果</th>
                        <th>備註</th>
                    </tr>
                </thead>
                <tbody>{{ help }}</tbody>
            </table>
        </div>
        </div>
    </div>
</body>
</html>
