<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>0118</title>
<link href="https://code.essoduke.org/css/style.css" rel="stylesheet" />
<style>
.map{width:100%;height:480px}
</style>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>常用指令清單</h2>
            </div>
        </div>
        <div class="row">
        <table class="table">
        <thead>
        <tr>
            <th>輸入指令</th>
            <th>結果</th>
        </tr>
        </thead>
        <tbody>{{ help|raw }}</tbody>
        </table>
        </div>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</body>
</html>
